### ISSUE TITLE
SockPage: When the variant changes, show the correct image

### ISSUE THREAD

**Issue by Laoujin** [itenium-be/React-New-Features#2]
Variants: blue socks, red socks, ...

```typescript
export interface SockVariantModel {
  id: number;
  color: string; // used for the image uri
  fancyColor: string; // color-box background color
}
```

Right now, the `SockVariantSelector` merely does a `console.log` of the new selected variant. Make the `const selectedVariant` variable.

- By turning the FunctionComponent to a class and using `setState`
- By using hooks

**Comment by patosz** [comment]
+1
